### ISSUE TITLE
Encounter RuntimeError when start itorch console

### ISSUE THREAD

**Issue by andrewliao11** [facebook/iTorch#126]
I got RuntimeError when command ```itorch```(use console)
```
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
/home/andrewliao11/torch/install/bin/luajit: ...andrewliao11/torch/install/share/lua/5.1/lzmq/poller.lua:99: attempt to call upvalue 'Poller' (a table value)
stack traceback:
        ...andrewliao11/torch/install/share/lua/5.1/lzmq/poller.lua:99: in function 'new'
        ...rewliao11/torch/install/share/lua/5.1/lzmq/impl/loop.lua:247: in function 'new'
        ...andrewliao11/torch/install/share/lua/5.1/itorch/main.lua:376: in main chunk
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x00406670
/home/andrewliao11/torch/install/bin/luajit: ...andrewliao11/torch/install/share/lua/5.1/lzmq/poller.lua:99: attempt to call upvalue 'Poller' (a table value)
stack traceback:
        ...andrewliao11/torch/install/share/lua/5.1/lzmq/poller.lua:99: in function 'new'
        ...rewliao11/torch/install/share/lua/5.1/lzmq/impl/loop.lua:247: in function 'new'
        ...wliao11/torch/install/share/lua/5.1/itorch/IOHandler.lua:120: in main chunk
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x00406670
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_console/app.py", line 137, in initialize
    self.init_shell()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_console/app.py", line 110, in init_shell
    client=self.kernel_client,
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_console/ptshell.py", line 251, in __init__
    self.init_kernel_info()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_console/ptshell.py", line 305, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request
```
My Ipython version is **5.1.0.dev**

I've tried ```itorch --simple-prompt```, mentioned in [issue](https://github.com/ipython/ipython/issues/9758)
It does start the itorch session, but got ipython kernel, instead of itorch

**Comment by murthy-dev** [comment]
luarocks install lzmq
