### ISSUE TITLE
Unable to start itorch session

### ISSUE THREAD

**Issue by gtm2122** [facebook/iTorch#147]
I installed iTorch as per instructions here https://github.com/facebook/iTorch
But whenever I try to start a kernel I get the following error 
gtm2122@GABRIEL:~/distro/iTorch$ itorch
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
Invalid argument (tcp_address.cpp:161)
/home/gtm2122/distro/install/bin/itorch_launcher: line 24:  8582 Aborted                 (core dumped) "$LUA" -e "arg={'$1','$IO_STDO','$IO_PORTNUM'};require 'itorch.IOHandler'"
Invalid argument (tcp_address.cpp:161)
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_console/app.py", line 137, in initialize
    self.init_shell()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_console/app.py", line 110, in init_shell
    client=self.kernel_client,
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_console/ptshell.py", line 251, in __init__
    self.init_kernel_info()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_console/ptshell.py", line 305, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request

**Comment by gtm2122** [comment]
fixed

**Comment by maroth** [comment]
Fixed where? I am facing the same issue, and the last commit on the public GitHub repo ist from October 2016, but your fix is from December 2016.
