### ISSUE TITLE
itorch_launcher: line 24: 127439 Segmentation fault

### ISSUE THREAD

**Issue by Sunarker** [facebook/iTorch#168]
Hi, all.

     I happened to meet the following problem when start with ``itorch" or ``itorch notebook"
 ------------------------------------------------------------------------------------------------------------------  
/home/jiayao/torch/install/bin/itorch_launcher: line 24: 127439 Segmentation fault      "$LUA" -e "arg={'$1','$IO_STDO','$IO_PORTNUM'};require 'itorch.IOHandler'"
Traceback (most recent call last):
  File "/home/jiayao/torch/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/home/jiayao/torch/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/jiayao/torch/lib/python2.7/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-115>", line 2, in initialize
  File "/home/jiayao/torch/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/jiayao/torch/lib/python2.7/site-packages/jupyter_console/app.py", line 141, in initialize
    self.init_shell()
  File "/home/jiayao/torch/lib/python2.7/site-packages/jupyter_console/app.py", line 114, in init_shell
    client=self.kernel_client,
  File "/home/jiayao/torch/lib/python2.7/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/home/jiayao/torch/lib/python2.7/site-packages/jupyter_console/ptshell.py", line 272, in __init__
    self.init_kernel_info()
  File "/home/jiayao/torch/lib/python2.7/site-packages/jupyter_console/ptshell.py", line 326, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request

------------------------------------------------------------------------------------------------------------------
     but firstly, I have installed all the required packages before install itorch.
           Secondly, I have tested ipython notebook and it works.
          But when I start with ``itorch" or ``itorch notebook", it crashed with above information

**Comment by Sunarker** [comment]
@soumith

**Comment by Sunarker** [comment]
@gtm2122
