### ISSUE TITLE
Failed to start the kernel

### ISSUE THREAD

**Issue by YamiNoKeshin** [facebook/iTorch#38]
I installed iTorch today, but every time when I try to start it via "ipython notebook" the kernel crashes with the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 407, in __get__
    value = obj._trait_values[self.name]
KeyError: 'session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 1247, in validate
    return bytes(value)
TypeError: string argument without an encoding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/IPython/html/base/handlers.py", line 365, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/usr/lib/python3.4/site-packages/IPython/html/services/sessions/handlers.py", line 53, in post
    model = sm.create_session(path=path, kernel_name=kernel_name)
  File "/usr/lib/python3.4/site-packages/IPython/html/services/sessions/sessionmanager.py", line 66, in create_session
    kernel_name=kernel_name)
  File "/usr/lib/python3.4/site-packages/IPython/html/services/kernels/kernelmanager.py", line 84, in start_kernel
    kernel_name=kernel_name, **kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/kernel/multikernelmanager.py", line 112, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/kernel/manager.py", line 224, in start_kernel
    self.write_connection_file()
  File "/usr/lib/python3.4/site-packages/IPython/kernel/connect.py", line 488, in write_connection_file
    transport=self.transport, ip=self.ip, key=self.session.key,
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 412, in __get__
    value = method()
  File "/usr/lib/python3.4/site-packages/IPython/kernel/connect.py", line 438, in _session_default
    return Session(parent=self)
  File "/usr/lib/python3.4/site-packages/IPython/kernel/zmq/session.py", line 430, in __init__
    super(Session, self).__init__(**kwargs)
  File "/usr/lib/python3.4/site-packages/IPython/config/configurable.py", line 80, in __init__
    self.config = config
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 445, in __set__
    obj._notify_trait(self.name, old_value, new_value)
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 602, in _notify_trait
    c(name, old_value, new_value)
  File "/usr/lib/python3.4/site-packages/IPython/config/configurable.py", line 159, in _config_changed
    self._load_config(new, traits=traits, section_names=section_names)
  File "/usr/lib/python3.4/site-packages/IPython/config/configurable.py", line 143, in _load_config
    setattr(self, name, deepcopy(config_value))
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 430, in __set__
    new_value = self._validate(obj, value)
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 451, in _validate
    return self.validate(obj, value)
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 1249, in validate
    self.error(obj, value)
  File "/usr/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 480, in error
    raise TraitError(e)
IPython.utils.traitlets.TraitError: The 'key' trait of a Session instance must be a bytes object, but a value of '' <class 'str'> was specified.

But if I start it with: 
"ipython notebook --profile torch" like it was before the fix from issue #33 it works without crashing. 

Arch Linux x64
iPython version: 3.0.0
Python version 3.4.3

**Comment by soumith** [comment]
we provide the itorch script for this reason:
"itorch notebook" should work

**Comment by YamiNoKeshin** [comment]
It doesn't for me, because (at least my install of) iPython doesn't accept an empty Session key. But I have no idea why

**Comment by kai-zhong** [comment]
Hi, i encounter this issue, too. i use command 'itorch notebook' to start, then new an iTorch notebook, but an kernel error display in the page.

Error Message:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 407, in __get__
    value = obj._trait_values[self.name]
KeyError: 'session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 1247, in validate
    return bytes(value)
TypeError: string argument without an encoding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/IPython/html/base/handlers.py", line 365, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/usr/local/lib/python3.4/site-packages/IPython/html/services/sessions/handlers.py", line 53, in post
    model = sm.create_session(path=path, kernel_name=kernel_name)
  File "/usr/local/lib/python3.4/site-packages/IPython/html/services/sessions/sessionmanager.py", line 66, in create_session
    kernel_name=kernel_name)
  File "/usr/local/lib/python3.4/site-packages/IPython/html/services/kernels/kernelmanager.py", line 84, in start_kernel
    kernel_name=kernel_name, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/IPython/kernel/multikernelmanager.py", line 112, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/IPython/kernel/manager.py", line 224, in start_kernel
    self.write_connection_file()
  File "/usr/local/lib/python3.4/site-packages/IPython/kernel/connect.py", line 488, in write_connection_file
    transport=self.transport, ip=self.ip, key=self.session.key,
  File "/usr/local/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 412, in __get__
    value = method()
  File "/usr/local/lib/python3.4/site-packages/IPython/kernel/connect.py", line 438, in _session_default
    return Session(parent=self)
  File "/usr/local/lib/python3.4/site-packages/IPython/kernel/zmq/session.py", line 433, in __init__
    super(Session, self).__init__(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/IPython/config/configurable.py", line 80, in __init__
    self.config = config
  File "/usr/local/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 445, in __set__
    obj._notify_trait(self.name, old_value, new_value)
  File "/usr/local/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 602, in _notify_trait
    c(name, old_value, new_value)
  File "/usr/local/lib/python3.4/site-packages/IPython/config/configurable.py", line 159, in _config_changed
    self._load_config(new, traits=traits, section_names=section_names)
  File "/usr/local/lib/python3.4/site-packages/IPython/config/configurable.py", line 143, in _load_config
    setattr(self, name, deepcopy(config_value))
  File "/usr/local/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 430, in __set__
    new_value = self._validate(obj, value)
  File "/usr/local/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 451, in _validate
    return self.validate(obj, value)
  File "/usr/local/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 1249, in validate
    self.error(obj, value)
  File "/usr/local/lib/python3.4/site-packages/IPython/utils/traitlets.py", line 480, in error
    raise TraitError(e)
IPython.utils.traitlets.TraitError: The 'key' trait of a Session instance must be a bytes object, but a value of '' <class 'str'> was specified.
```

I use following instruction to install iTorch:
1. pip install 'ipython[all]'
2. luarocks install itorch

PS:torch had been installed in my mac.

My mac env:
* OS X Yosmite 10.10.3
* Python 3.4.3

how can i fix it? thanks~~~
