### ISSUE TITLE
Install iTorch on Mac crashes

### ISSUE THREAD

**Issue by watts4speed** [facebook/iTorch#71]
I'm installing iTorch on mac and when I run itorch I get a crash.  I'm sure I'm doing something pretty dumb but I can't figure out what.

Thanks in advance!

Here's my log:

pmerrill-osx:extra pmerrill$ brew install zeromq
Warning: zeromq-4.1.3 already installed
pmerrill-osx:extra pmerrill$ brew install openssl
Warning: openssl-1.0.2d_1 already installed
pmerrill-osx:extra pmerrill$ luarocks install luacrypto OPENSSL_DIR=/usr/local/opt/openssl/
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luacrypto-0.3.2-1.src.rock...
Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luacrypto-0.3.2-1.src.rock... switching to 'build' mode
Archive:  0.3.2.zip
0639ea2f65dbe5f11c2d874527f3019ce5293ac5
   creating: luacrypto-0.3.2/
  inflating: luacrypto-0.3.2/.gitignore  
 extracting: luacrypto-0.3.2/AUTHORS  
  inflating: luacrypto-0.3.2/CMakeLists.txt  
  inflating: luacrypto-0.3.2/COPYING  
  inflating: luacrypto-0.3.2/ChangeLog  
  inflating: luacrypto-0.3.2/INSTALL  
  inflating: luacrypto-0.3.2/Makefile.am  
  inflating: luacrypto-0.3.2/Makefile.in  
 extracting: luacrypto-0.3.2/NEWS    
  inflating: luacrypto-0.3.2/README  
  inflating: luacrypto-0.3.2/aclocal.m4  
  inflating: luacrypto-0.3.2/config.guess  
  inflating: luacrypto-0.3.2/config.h.in  
  inflating: luacrypto-0.3.2/config.sub  
  inflating: luacrypto-0.3.2/configure  
  inflating: luacrypto-0.3.2/configure.ac  
  inflating: luacrypto-0.3.2/depcomp  
  inflating: luacrypto-0.3.2/dist.cmake  
   creating: luacrypto-0.3.2/doc/
  inflating: luacrypto-0.3.2/doc/Makefile.am  
  inflating: luacrypto-0.3.2/doc/Makefile.in  
   creating: luacrypto-0.3.2/doc/us/
  inflating: luacrypto-0.3.2/doc/us/examples.html  
  inflating: luacrypto-0.3.2/doc/us/index.html  
  inflating: luacrypto-0.3.2/doc/us/license.html  
  inflating: luacrypto-0.3.2/doc/us/luacrypto-128.png  
  inflating: luacrypto-0.3.2/doc/us/manual.html  
  inflating: luacrypto-0.3.2/install-sh  
  inflating: luacrypto-0.3.2/ltmain.sh  
  inflating: luacrypto-0.3.2/luacrypto.pc.in  
  inflating: luacrypto-0.3.2/luacrypto.sln  
  inflating: luacrypto-0.3.2/luacrypto.vcproj  
   creating: luacrypto-0.3.2/m4/
  inflating: luacrypto-0.3.2/m4/libtool.m4  
  inflating: luacrypto-0.3.2/m4/ltoptions.m4  
  inflating: luacrypto-0.3.2/m4/ltsugar.m4  
  inflating: luacrypto-0.3.2/m4/ltversion.m4  
  inflating: luacrypto-0.3.2/m4/lt~obsolete.m4  
  inflating: luacrypto-0.3.2/missing  
   creating: luacrypto-0.3.2/rockspecs/
  inflating: luacrypto-0.3.2/rockspecs/luacrypto-git-1.rockspec  
   creating: luacrypto-0.3.2/src/
  inflating: luacrypto-0.3.2/src/Makefile.am  
  inflating: luacrypto-0.3.2/src/Makefile.in  
  inflating: luacrypto-0.3.2/src/lcrypto.c  
  inflating: luacrypto-0.3.2/src/lcrypto.h  
   creating: luacrypto-0.3.2/tests/
  inflating: luacrypto-0.3.2/tests/Makefile.am  
  inflating: luacrypto-0.3.2/tests/Makefile.in  
   creating: luacrypto-0.3.2/tests/ca/
  inflating: luacrypto-0.3.2/tests/ca/README  
  inflating: luacrypto-0.3.2/tests/ca/ca.crt  
  inflating: luacrypto-0.3.2/tests/ca/ca.key  
  inflating: luacrypto-0.3.2/tests/ca/server.crt  
  inflating: luacrypto-0.3.2/tests/ca/server.csr  
  inflating: luacrypto-0.3.2/tests/ca/server.key  
  inflating: luacrypto-0.3.2/tests/ca/server.key.insecure  
  inflating: luacrypto-0.3.2/tests/encrypt.lua  
 extracting: luacrypto-0.3.2/tests/message  
  inflating: luacrypto-0.3.2/tests/open_seal.lua  
  inflating: luacrypto-0.3.2/tests/pkeytest.lua  
  inflating: luacrypto-0.3.2/tests/rand.lua  
  inflating: luacrypto-0.3.2/tests/run-tests  
  inflating: luacrypto-0.3.2/tests/test.lua  
 extracting: luacrypto-0.3.2/tests/tmp.rnd  
  inflating: luacrypto-0.3.2/tests/x509_ca.lua  
export MACOSX_DEPLOYMENT_TARGET=10.5; gcc -O2 -fPIC -I/Users/pmerrill/torch/install/include -c src/lcrypto.c -o src/lcrypto.o -I/usr/local/opt/openssl/include
export MACOSX_DEPLOYMENT_TARGET=10.5; gcc -bundle -undefined dynamic_lookup -all_load -o crypto.so -L/Users/pmerrill/torch/install/lib src/lcrypto.o -L/usr/local/opt/openssl/lib -Wl,-rpath,/usr/local/opt/openssl/lib: -lcrypto
Updating manifest for /Users/pmerrill/torch/install/lib/luarocks/rocks
luacrypto 0.3.2-1 is now built and installed in /Users/pmerrill/torch/install/ (license: MIT)

pmerrill-osx:extra pmerrill$ git clone https://github.com/facebook/iTorch.git
fatal: destination path 'iTorch' already exists and is not an empty directory.
pmerrill-osx:extra pmerrill$ cd iTorch
pmerrill-osx:iTorch pmerrill$ luarocks make
   ipy=$(which ipython)   
   if [ -x "$ipy" ]
   then
	ipybase=$(ipython locate)
	rm -rf $ipybase/profile_torch
	ipython profile create torch
	echo 'c.KernelManager.kernel_cmd = ["/Users/pmerrill/torch/install/bin/itorch_launcher","{connection_file}"]' >>$ipybase/profile_torch/ipython_config.py   	
	echo "c.Session.key = b''" >>$ipybase/profile_torch/ipython_config.py
	echo "c.Session.keyfile = b''" >>$ipybase/profile_torch/ipython_config.py
	mkdir -p $ipybase/profile_torch/static/base/images
	mkdir -p $ipybase/kernels/itorch
	cat kernelspec/kernel.json | sed "s@LUA_BINDIR@/Users/pmerrill/torch/install/bin@" > $ipybase/kernels/itorch/kernel.json
	cp kernelspec/*.png $ipybase/kernels/itorch/
	cp ipynblogo.png $ipybase/profile_torch/static/base/images
	mkdir -p $ipybase/profile_torch/static/custom/
	cp custom.js $ipybase/profile_torch/static/custom/
	cp custom.css $ipybase/profile_torch/static/custom/
	cp itorch /Users/pmerrill/torch/install/bin/
	cp itorch_launcher /Users/pmerrill/torch/install/bin/
	cp -r ~/.ipython/profile_torch ~/.ipython/profile_itorch
	cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/Users/pmerrill/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/Users/pmerrill/torch/install/lib/luarocks/rocks/itorch/scm-1" && make	
   else
	echo "Error: could not find ipython in PATH. Do you have it installed?"
   fi
  

[ProfileCreate] Generating default config file: u'/Users/pmerrill/.ipython/profile_torch/ipython_config.py'
-- Found Torch7 in /Users/pmerrill/torch/install
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/pmerrill/torch/extra/iTorch/build
cd build && make install
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/pmerrill/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/_env.lua
-- Installing: /Users/pmerrill/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/bokeh.lua
-- Installing: /Users/pmerrill/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/completer.lua
-- Installing: /Users/pmerrill/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/gfx.lua
-- Installing: /Users/pmerrill/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/init.lua
-- Installing: /Users/pmerrill/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/IOHandler.lua
-- Installing: /Users/pmerrill/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/main.lua
-- Installing: /Users/pmerrill/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/Plot.lua
-- Installing: /Users/pmerrill/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/test.lua
-- Installing: /Users/pmerrill/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/util.lua
-- Installing: /Users/pmerrill/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/bokeh-0.7.0.min.js
-- Installing: /Users/pmerrill/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/bokeh-0.7.0.min.css
Updating manifest for /Users/pmerrill/torch/install/lib/luarocks/rocks
itorch scm-1 is now built and installed in /Users/pmerrill/torch/install/ (license: BSD)

pmerrill-osx:iTorch pmerrill$ 
pmerrill-osx:iTorch pmerrill$ itorch
/Users/pmerrill/torch/install/bin/itorch: line 19: jupyter: command not found
pmerrill-osx:iTorch pmerrill$ itorch notebook
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Library/Python/2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Library/Python/2.7/site-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/Library/Python/2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Library/Python/2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/Library/Python/2.7/site-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/Library/Python/2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/Library/Python/2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/Library/Python/2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named notebook.notebookapp
pmerrill-osx:iTorch pmerrill$

**Comment by soumith** [comment]
have you installed ipython / jupyter? it seems to say:  jupyter: command not found

**Comment by watts4speed** [comment]
Cool thanks that did the trick!!!  I needed a sudo infront of the pip to get jupyter to install.

I'm testing and finding that the image/audio/video are not working.  Here's an example of the output console log where the image is not drawing like in the example.  Any ideas what might be going on?
Thanks again in advance!

"In [2]: itorch.image({image.lena(), image.lena(), image.lena()})
Out[2]: 



In [3]: "

**Comment by soumith** [comment]
They don't work in itorch console, you'll have to open an itorch notebook
(that opens in the browser)
