### ISSUE TITLE
Unable to install on Ubuntu

### ISSUE THREAD

**Issue by adeshpande3** [facebook/iTorch#82]
Hi all, I am unable to install on Linux Ubuntu 14.04. I have iPython installed so I'm not sure what could be the issue. I'm guessing that its a problem with the Path to ipython? I'd appreciate any help. 

adeshpande@adeshpande-VirtualBox:~/torch/iTorch$ sudo env "PATH=$PATH" luarocks make
[sudo] password for adeshpande: 
   ipy=$(which ipython)   
   if [ -x "$ipy" ]
   then
	ipybase=$(ipython locate)
	rm -rf $ipybase/profile_torch
	ipython profile create torch
	echo 'c.KernelManager.kernel_cmd = ["/home/adeshpande/torch/install/bin/itorch_launcher","{connection_file}"]' >>$ipybase/profile_torch/ipython_config.py   	
	echo "c.Session.key = b''" >>$ipybase/profile_torch/ipython_config.py
	echo "c.Session.keyfile = b''" >>$ipybase/profile_torch/ipython_config.py
	mkdir -p $ipybase/profile_torch/static/base/images
	mkdir -p $ipybase/kernels/itorch
	cat kernelspec/kernel.json | sed "s@LUA_BINDIR@/home/adeshpande/torch/install/bin@" > $ipybase/kernels/itorch/kernel.json
	cp kernelspec/*.png $ipybase/kernels/itorch/
	cp ipynblogo.png $ipybase/profile_torch/static/base/images
	mkdir -p $ipybase/profile_torch/static/custom/
	cp custom.js $ipybase/profile_torch/static/custom/
	cp custom.css $ipybase/profile_torch/static/custom/
	cp itorch /home/adeshpande/torch/install/bin/
	cp itorch_launcher /home/adeshpande/torch/install/bin/
	cp -r ~/.ipython/profile_torch ~/.ipython/profile_itorch
	cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/adeshpande/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/adeshpande/torch/install/lib/luarocks/rocks/itorch/scm-1" && make	
   else
	echo "Error: could not find ipython in PATH. Do you have it installed?"
   fi
  

[ProfileCreate] Generating default config file: u'/home/adeshpande/.ipython/profile_torch/ipython_config.py'
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/adeshpande/torch/install
-- Configuring done
-- Generating done
-- Build files have been written to: /home/adeshpande/torch/iTorch/build
cd build && make install
Install the project...
-- Install configuration: "Release"
-- Installing: /home/adeshpande/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/completer.lua
-- Installing: /home/adeshpande/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/Plot.lua
-- Installing: /home/adeshpande/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/IOHandler.lua
-- Installing: /home/adeshpande/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/init.lua
-- Installing: /home/adeshpande/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/test.lua
-- Installing: /home/adeshpande/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/util.lua
-- Installing: /home/adeshpande/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/gfx.lua
-- Installing: /home/adeshpande/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/main.lua
-- Installing: /home/adeshpande/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/_env.lua
-- Installing: /home/adeshpande/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/bokeh.lua
-- Installing: /home/adeshpande/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/bokeh-0.7.0.min.js
-- Installing: /home/adeshpande/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/bokeh-0.7.0.min.css
Updating manifest for /home/adeshpande/torch/install/lib/luarocks/rocks
itorch scm-1 is now built and installed in /home/adeshpande/torch/install/ (license: BSD)

**Comment by soumith** [comment]
it seems to have installed fine. what is the problem?

**Comment by adeshpande3** [comment]
I'm should be done with the installation process at this point right? When I try running itorch notebook, this is what I get:

adeshpande@adeshpande-VirtualBox:~/torch/iTorch$ itorch notebook
Traceback (most recent call last):
  File "/usr/bin/ipython", line 5, in <module>
    start_ipython()
  File "/home/adeshpande/.local/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/adeshpande/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/home/adeshpande/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/adeshpande/.local/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/adeshpande/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/adeshpande/.local/lib/python2.7/site-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/home/adeshpande/.local/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/home/adeshpande/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/adeshpande/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/home/adeshpande/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/adeshpande/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/home/adeshpande/.local/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
  File "/home/adeshpande/.local/lib/python2.7/site-packages/notebook/notebookapp.py", line 28, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/home/adeshpande/.local/lib/python2.7/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/home/adeshpande/.local/lib/python2.7/site-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/home/adeshpande/.local/lib/python2.7/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/home/adeshpande/.local/lib/python2.7/site-packages/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe

**Comment by soumith** [comment]
that looks like an issue with ipython, not with itorch.

**Comment by adeshpande3** [comment]
Do we need to download Anaconda or Canopy for itorch to work?

**Comment by soumith** [comment]
not really, a system ipython should do. Do you have normal behavior in "ipython notebook"? 
Also can you tell me your ipython version?

**Comment by soumith** [comment]
it seems that you have the same issue as here: http://stackoverflow.com/questions/18412136/ipython-notebook-with-scipysuperpack-missing-markupsafe-dependency

**Comment by adeshpande3** [comment]
Ok thank you, I unistalled pip, reinstalled it, and then installed ipython again and it worked out. Thanks!
