### ISSUE TITLE
iTorch times-out during nn training w/ GPU

### ISSUE THREAD

**Issue by elbamos** [facebook/iTorch#91]
Whenever I tell torch to run a more-than-very-short (i.e., 15 minute) nn training, eventually the notebook interface becomes entirely unresponsive and I begin seeing errors like this on the  console:

```
[I 21:22:59.151 NotebookApp] Adapting to protocol v4.0 for kernel 1631fc98-f934-4d40-a99f-2f72e3c7d639
[W 21:24:29.153 NotebookApp] WebSocket ping timeout after 90001 ms.
[E 21:24:29.160 NotebookApp] Uncaught exception GET /api/kernels/1631fc98-f934-4d40-a99f-2f72e3c7d639/channels?session_id=12FE8B4319874D87A27A057461B4FB7E (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/1631fc98-f934-4d40-a99f-2f72e3c7d639/channels?session_id=12FE8B4319874D87A27A057461B4FB7E', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Upgrade': 'websocket', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Sec-Websocket-Version': '13', 'Host': 'localhost:8888', 'Sec-Websocket-Key': 'nGMIH0RdWwxDy4Z8pJb42Q==', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.48 Safari/537.36', 'Dnt': '1', 'Connection': 'Upgrade', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits'})
    Traceback (most recent call last):
      File "/Volumes/home500/anaconda/envs/amos27/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/Volumes/home500/anaconda/envs/amos27/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/Volumes/home500/anaconda/envs/amos27/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/Volumes/home500/anaconda/envs/amos27/lib/python2.7/site-packages/notebook/base/zmqhandlers.py", line 188, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/Volumes/home500/anaconda/envs/amos27/lib/python2.7/site-packages/tornado/websocket.py", line 200, in write_message
        raise WebSocketClosedError()
    WebSocketClosedError
```

Perhaps not unrelated, after control-c'ing out of ipython, often multiple `qlua` and/or `luajit` processes continue to run, with at least one consuming an entire core.  

I've tried, e.g., telling my training script to send more updates to the notebook, but to no avail.  (I noticed there are some comments in the `itorch` package source where you overload `xlua:progress()` about the frequency of notebook updates.)

I'm running Mac OS X 10.11.2 using CUDA 7.5 on a GTX 980.  

Advice? :)

**Comment by soumith** [comment]
oh, that seems annoying. I didn't realize that Jupyter had a 90001 ms timeout on it's kernels. I'll try to first reproduce, and then find a workaround.
