### ISSUE TITLE
When I run itorch or when I start a new itorch web in itorch notebook, the following happens

### ISSUE THREAD

**Issue by sluo1989** [facebook/iTorch#94]
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/paths.py:62: UserWarning: IPython dir '/Users/Shikai/.ipython' is not a writable location, using a temp directory.
  " using a temp directory.".format(ipdir))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-114>", line 2, in initialize
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jupyter_console/app.py", line 136, in initialize
    self.init_shell()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jupyter_console/app.py", line 103, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jupyter_client/consoleapp.py", line 329, in initialize
    self.init_kernel_manager()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jupyter_client/consoleapp.py", line 283, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jupyter_client/manager.py", line 244, in start_kernel
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jupyter_client/manager.py", line 190, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I am running on MacOSX 10.11, have all newest version jupter ipython itorch installed...

Please help me out:-) 

Thanks!

**Comment by nguyenductung** [comment]
Hi, I'm facing with the same issue on Ubuntu 14.04. Could somebody help us?
```python
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_console/app.py", line 138, in initialize
    self.init_shell()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_console/app.py", line 105, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/consoleapp.py", line 334, in initialize
    self.init_kernel_manager()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/consoleapp.py", line 288, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/manager.py", line 243, in start_kernel
    **kw)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by liuchang8am** [comment]
Having the same problem on OSX

`Traceback (most recent call last):
  File "/Users/lc/anaconda/bin/jupyter-console", line 5, in <module>
    app.main()
  File "/Users/lc/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/lc/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-114>", line 2, in initialize
  File "/Users/lc/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/lc/anaconda/lib/python2.7/site-packages/jupyter_console/app.py", line 136, in initialize
    self.init_shell()
  File "/Users/lc/anaconda/lib/python2.7/site-packages/jupyter_console/app.py", line 103, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/Users/lc/anaconda/lib/python2.7/site-packages/jupyter_client/consoleapp.py", line 329, in initialize
    self.init_kernel_manager()
  File "/Users/lc/anaconda/lib/python2.7/site-packages/jupyter_client/consoleapp.py", line 283, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/Users/lc/anaconda/lib/python2.7/site-packages/jupyter_client/manager.py", line 244, in start_kernel
    **kw)
  File "/Users/lc/anaconda/lib/python2.7/site-packages/jupyter_client/manager.py", line 190, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/lc/anaconda/lib/python2.7/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Users/lc/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/lc/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

Any help?

**Comment by cemysf** [comment]
had the same error
clearing all old jupyter kernels in `~/.local/share/jupyter/kernels/`  and reinstalling iTorch solved it
